### PR TITLE
Update UML2's setup to work with the new clone location

### PR DESCRIPTION
**Pull request by merks**
Also provide improved root files that render well in GitHub.

### CODE REVIEW

**Comment by merks** [comment]
This include providing a nice link as seen here:

https://github.com/merks/uml2/blob/pr-fix-setup/CONTRIBUTING.md

**Comment by merks** [comment]
@khussey 

For the good of your community, you really ought to merge such changes relatively quickly.  These changes have no impact on the build but rather simply improve a contributor's ability to contribute...

**Review by khussey — APPROVED** [review]
Oh wow, thanks so much for the contribution, @merks ! I only just noticed this pull request after you mentioned me in your more recent comment; I've updated my notification settings to include all activity going forward.

**Comment by merks** [comment]
I figured an oversight was involved.  👍 

BTW, you should ask the helpdesk

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues

to create a .github repo and a .eclipsefdn repo like EMF has those.

https://github.com/orgs/eclipse-emf/repositories

They will know what you need and why you needed.  The former lets you create documentation visible on the organization home page, e.g.,

https://github.com/eclipse-emf/.github/blob/main/profile/README.md

The latter lets you do self-service configuration of your organization and its repositories by editing this corresponding file:

https://github.com/eclipse-emf/.eclipsefdn/blob/main/otterdog/eclipse-emf.jsonnet

**Comment by khussey** [comment]
> BTW, you should ask the helpdesk
> 
> https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues

[Done](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4036), thanks for the recommendation!

**Comment by merks** [comment]
FYI, I'll help with some of the .github things when I'm back from traveling this week, during the coming quiet period.  😄

**Pull request merged**
